version: "3.1"

services:
  web:
    image: nginx:1.14
    working_dir: /app
    volumes:
      - ./app:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8888:80

  app:
    image: adnanahmady/php:1.0.4
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      DB_HOST: database
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - database
      - redis

  redis:
    image: redis:5.0
    expose:
      - 6379

  database:
    image: postgres:10.5
    environment:
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: homestead
  
  adminer:
    image: adminer
    ports:
      - 8083:8080
